### ISSUE TITLE
reimplement wslpy.exec

### ISSUE THREAD

**Issue by shubhsboson** [wslutilities/wslpy#14]

**Comment by shubhsboson** [comment]
# Info required
  Information required on what exactly is to be re-implemented or the crucial changes required.

**Comment by shubhsboson** [comment]
Hey! @patrick330602  can we discuss this when you find time ?

**Comment by patrick330602** [comment]
> Hey! @patrick330602 can we discuss this when you find time ?

Yes, please! I am currently writing guidelines for the contribution though, so the response time will be slow

**Comment by shubhsboson** [comment]
Copy That!

**Comment by shubhsboson** [comment]
So shall we schedule a discussion or just ask in this thread ?

**Comment by patrick330602** [comment]
Just straight up discuss here please.

**Comment by shubhsboson** [comment]
As I have asked before 
> Information required on what exactly is to be re-implemented or the crucial changes required.

**Comment by patrick330602** [comment]
Currently it will just execute commands and that is all. Jut it currently have issues:
1. It assumes the distribution appends the Windows path to the $PATH variable;
2. It do not make sure the running distribution have Interop enabled;
3. It cannot separate STDOUT and STDERR;
4. It cannot directly provide error code to users.

Basically the re-implementation will need to do solve the four issues.

Here is the checklist that help you to follow up:
- [ ] It assumes the distribution appends the Windows path to the $PATH variable;
- [ ] It do not make sure the running distribution have Interop enabled;
- [ ] It cannot separate STDOUT and STDERR;
- [ ] It cannot directly provide error code to users.

**Comment by shubhsboson** [comment]
Solid copy!!

**Comment by shubhsboson** [comment]
#17
