### ISSUE TITLE
[TEAM][Priority: 5][Library: wslpy.system] Distro detection

### ISSUE THREAD

**Issue by patrick330602** [wslutilities/wslpy#19]
Ref: https://github.com/wslutilities/wslu/blob/221e85457c01e92db675cc7b24a49dfcdfacc6a9/src/wslu-header#L240-L257

**Comment by shubhsboson** [comment]
Hi Patrick ! I've linked a crude implementation of distro detection please review it.

Also here ,

> distro="$(head -n1 /etc/os-release | sed -e 's/NAME=\"//g')"
case $distro in
	*Pengwin*) distro="pengwin";;
	*WLinux*) distro="wlinux";;
	Ubuntu*) distro="ubuntu";;
	*Debian*) distro="debian";;
	*Kali*) distro="kali";;
	openSUSE*) distro="opensuse";;
	SLES*) distro="sles";;
	Alpine*) distro="alpine";;
	Arch*) distro="archlinux";;
	*Oracle*) distro="oracle";;
	Scientific*) distro="scilinux";;
	*Fedora\ Remix\ for\ WSL*) distro="fedoraremix";;
	*Fedora*) distro="fedora";;
	*Generic*) [ "fedora" == "$(grep -e "LIKE=" /etc/os-release | sed -e 's/ID_LIKE=//g')" ] && distro="oldfedora" || distro="unknown";;
	*) distro="unknown";;
esac

I see you've used switch cases , but I am unable to undersatnd the need of it.

**Comment by patrick330602** [comment]
I have answered your question in the PR Request Changes.

**Comment by shubhsboson** [comment]
Copy that !
