### ISSUE TITLE
isWSL always returns True

### ISSUE THREAD

**Issue by juntalis** [wslutilities/wslpy#3]
[pathlib.Path.resolve](https://github.com/wslutilities/wslpy/blob/81aa954c5ca7c835b6b1c566e01876291bf1594a/wslpy/__init__.py#L6) doesn't verify the existence of the path - it just builds it based on your input and converts it to the OS-specific format. As a result, `isWSL` would always return `True`.

```python
>>> from pathlib import Path
>>> p = Path('/proc/sys/fs/binfmt_misc/WSLInterop').resolve()
>>> p
WindowsPath('C:/proc/sys/fs/binfmt_misc/WSLInterop')
>>> p.exists()
False
```

**Comment by patrick330602** [comment]
the bug is reproduced. Fix is on the way

**Comment by patrick330602** [comment]
Implemented, closed
