### ISSUE TITLE
Module 'wslpy' has no attribute 'convert' (i.e. documentation out of sync)

### ISSUE THREAD

**Issue by fridde** [wslutilities/wslpy#4]
Is it possible that your documentation given in README.md represents some older architecture?
None of your examples 
```
wslpy.isWSL
wslpy.convert.reg_list()
wslpy.convert.from_reg(input)
wslpy.convert.to_path(input, toType = PathConvType.AUTO)
wslpy.winsys.build
wslpy.winsys.branch
wslpy.winsys.long_build
wslpy.winsys.CmdExec(command)
wslpy.winsys.PwShExec(command)
wslpy.winsys.PwShCrExec(command)
```
can work. 

```isWSL``` is a function, not an attribute. And neither ```convert``` nor ```winsys``` are imported into the module, so any of the lines above would just give ```module 'wslpy' has no attribute 'winsys'``` (or 'convert')

Would you mind updating either the documentation or your ```__init__.py``` to reflect your new module structure? 

This little tool was what I had been looking for and it would be a shame if it became unusable for others. And I don't want to create a pull request as the changes need a decision best made by the author, I think (change the docs or ```__init__.py``` ?)

**Comment by patrick330602** [comment]
Sorry about the inconvenience caused. The documentation listed is outdated. I will update the information.

Also, I am still working on `wslpy` so there will be changes in the future.

**Comment by fridde** [comment]
Thanks! 
I personally thinks it works just fine if you "ignore" the docs, so having them around confuses more than it helps :-D

Example: convert.to_path() has become convert.to() and that took me a while to find out.

**Comment by patrick330602** [comment]
I have updated the doc and upload a new version to pypi.
Also, this version removed some of the features from old version, so something might not work properly.

**Comment by fridde** [comment]
Awesome!
Works like a charm! Thank you very much!
