### ISSUE TITLE
Looking for Maintainers

### ISSUE THREAD

**Issue by patrick330602** [wslutilities/wslpy#7]
## Why looking for maintainers?

I am currently working in Canonical (as you might already know) to work on Ubuntu for WSL and Ubuntu for Hyper-V. With the works I have, while spending my free time on building wslu, I find myself unable to spare enough time for `wslpy`. Hence, I am looking for one or two maintainers to help to complete and improving this project.

## What should I do?

Currently, `wslpy` is half baked if you look into the code. Here are the current TO-DOs:

- implement wslpy.system;
  - implement `registry(input, key)`;
  - implement `RegEnvVarList()` using `__regInfoFetch__(input, key)`;
  - implement `regEnvVar(input)` to get environment variables via Registry.
- reimplement wslpy.exec.

Here are the goals:

- implement the same features provided by `wslvar`, `wslsys` and `wslupath` from `wslu`;
- (Optional) implement features by `wslusc` and `wslact` from `wslu`;
- Build a documentation/wiki for the project.

## What should I do to become a maintainer?

You should submit at least one PR to the project for fixing one of the issues in TO-DOs. Once it is reviewed and merged, I will add you to the maintainer list. I will be using IRC for communication (#wslu in Freenode.net). You will also get an email address ending with wslutiliti.es with your name.

**Comment by HayashiEsme** [comment]
Hey, I had a look at the code and I'd love to implement registry(input, key). I worked with Python at my old job running a codebase people were reliant on on my own so I'd love to give this a good shot:) (I might bother you with documentation format questions though:P)

**Comment by patrick330602** [comment]
> Hey, I had a look at the code and I'd love to implement registry(input, key). I worked with Python for a few years now and professionally at my old job for tooling running a codebase people were reliant on on my own so I'd love to give this a good shot:) (I might bother you with documentation format questions though:P)

You can just straight up working on the code and submit a PR ;)

**Comment by HayashiEsme** [comment]
I'll also be implementing RegEnvVarList() and regEnvVar(input), since I've been working on Registry()
