### ISSUE TITLE
Implement wslpy.system

### ISSUE THREAD

**Issue by shubhsboson** [wslutilities/wslpy#8]
- implement wslpy.system;
   - implement registry(input, key);
   - implement RegEnvVarList() using __regInfoFetch__(input, key);
   - implement regEnvVar(input) to get environment variables via Registry.

**Comment by patrick330602** [comment]
- implement `wslpy.system`: 
  for the current stage, it is expected to implement the feature provided by `wslvar` in `wslu`: https://github.com/wslutilities/wslu/blob/master/src/wslvar.sh
  - implement registry(input, key): 
    This function expect a registry path as `input` and the key item as `key`. The output should be its value; The optimal goal will be returning both the key type(Is it a string, a hex value, or something else?) and the key value in the proper format. This is currently being built with `__regInfoFetch__(input, key)`
  - implement RegEnvVarList() using regInfoFetch(input, key): 
    should achieve the same goal as the following function in `wslvar`, as it lists the system environment variables stored in registry:
    **https://github.com/wslutilities/wslu/blob/248304be6ddf850a567d08b9eabc239f0b9f0e4b/src/wslvar.sh#L12-L14**
  - implement regEnvVar(input) to get environment variables via Registry:
    should achieve the same goal as the following function in `wslvar`, as it give value of the system environment variables stored in registry with the key name specified:
    **https://github.com/wslutilities/wslu/blob/248304be6ddf850a567d08b9eabc239f0b9f0e4b/src/wslvar.sh#L8-10**

**Comment by shubhsboson** [comment]
> * implement `wslpy.system`:
>   for the current stage, it is expected to implement the feature provided by `wslvar` in `wslu`: https://github.com/wslutilities/wslu/blob/master/src/wslvar.sh
>   
>   * implement registry(input, key):
>     This function expect a registry path as `input` and the key item as `key`. The output should be its value; The optimal goal will be returning both the key type(Is it a string, a hex value, or something else?) and the key value in the proper format. This is currently being built with `__regInfoFetch__(input, key)`
>   * implement RegEnvVarList() using regInfoFetch(input, key):
>     should achieve the same goal as the following function in `wslvar`, as it lists the system environment variables stored in registry:
>     **https://github.com/wslutilities/wslu/blob/248304be6ddf850a567d08b9eabc239f0b9f0e4b/src/wslvar.sh#L12-L14**

 Did you actually mean **implement  RegEnvVarList() like [view_sys](https://github.com/wslutilities/wslu/blob/248304be6ddf850a567d08b9eabc239f0b9f0e4b/src/wslvar.sh#L20-22) instead of [view_shell](https://github.com/wslutilities/wslu/blob/248304be6ddf850a567d08b9eabc239f0b9f0e4b/src/wslvar.sh#L12-L14)(which is actually what the link refers to)** and is already being implemented by [shellEnvVarList()](https://github.com/wslutilities/wslpy/blob/11d2beee6e2196d3f6798246b12970ad889b1176/wslpy/system.py#L48-56)

>   * implement regEnvVar(input) to get environment variables via Registry:
>     should achieve the same goal as the following function in `wslvar`, as it give value of the system environment variables stored in registry with the key name specified:
>     **https://github.com/wslutilities/wslu/blob/248304be6ddf850a567d08b9eabc239f0b9f0e4b/src/wslvar.sh#L8-10**

And similarly **implement   regEnvVar(input) like [call_sys](https://github.com/wslutilities/wslu/blob/248304be6ddf850a567d08b9eabc239f0b9f0e4b/src/wslvar.sh#L16-18) instead of [call_shell](https://github.com/wslutilities/wslu/blob/248304be6ddf850a567d08b9eabc239f0b9f0e4b/src/wslvar.sh#L8-10)(which is actually what the link refers to)** and is already being implemented by [shellEnvVar(input)](https://github.com/wslutilities/wslpy/blob/11d2beee6e2196d3f6798246b12970ad889b1176/wslpy/system.py#L59-77)

**Comment by patrick330602** [comment]
> Did you actually mean implement RegEnvVarList() like view_sys instead of view_shell(which is actually what the link refers to) and is already being implemented by shellEnvVarList().
> And similarly implement regEnvVar(input) like call_sys instead of call_shell(which is actually what the link refers to) and is already being implemented by shellEnvVar(input)
Yeah you are right. You should rename it to` SysEnvVarList()`, and build `sysEnvVar(input)` instead. I am too exhausted recently and got absent-minded, sorry for that

**Comment by shubhsboson** [comment]
Hauna Matata 😄

**Comment by shubhsboson** [comment]
Pr #9 fixes this

**Comment by shubhsboson** [comment]
pr #9 has been merged so , closing this issue.
